import configparser
import distutils.command.clean
import os
import sys
from distutils.core import setup
from distutils.extension import Extension

from Cython.Build import cythonize

# Project metadata lives in pyproject.toml ([project] table).


class clean(distutils.command.clean.clean):
    description = (
        distutils.command.clean.clean.description
        + ", and print how to remove the generated and compiled files"
    )

    def run(self):
        out = super().run()
        print("""
The files generated by Cython (*.c) and the compiled extension modules
(*.so, *.pyd), as well as the __pycache__ directories, are *not* removed by
this command. Since they are all git-ignored, they can be removed with

    git clean -Xfd janus/

Beware: the janus/ argument is mandatory. Without it, git clean would also
delete setup.cfg, which is git-ignored.
""")
        return out


def update_from_config(kwargs, section):
    """Merge the specified section of ``setup.cfg`` into ``kwargs``.

    The ``include_dirs``, ``library_dirs`` and ``libraries`` entries of the
    section are read as comma-separated lists, and appended to the values
    already stored in ``kwargs`` (a dictionary that can be passed to
    Extension()). A missing section, or a missing/empty entry, is ignored.

    ``kwargs`` is updated in place and returned.
    """
    config = configparser.ConfigParser()
    config.read("setup.cfg")
    if config.has_section(section):
        for key in ["include_dirs", "library_dirs", "libraries"]:
            value = config[section].get(key, "")
            if value != "":
                kwargs[key] = kwargs.get(key, []) + [
                    token.strip() for token in value.split(",")
                ]
    return kwargs


def fftw_config():
    """Return the keyword arguments of Extension() that locate FFTW.

    These are read from the ``[fftw]`` section of ``setup.cfg``. If this file
    provides no entry, defaults suitable for a conda environment are used:
    ``libraries = fftw3`` on all platforms and, on Windows, the ``include``
    and ``lib`` subdirectories of ``sys.prefix\\Library``, where conda
    installs FFTW. On Linux and macOS, the Python interpreter provided by
    conda already passes the paths of the environment to the compiler.
    """
    kwargs = update_from_config({}, "fftw")
    if kwargs:
        return kwargs
    kwargs = {"libraries": ["fftw3"]}
    is_conda = os.path.isdir(os.path.join(sys.prefix, "conda-meta"))
    if sys.platform == "win32" and is_conda:
        library = os.path.join(sys.prefix, "Library")
        kwargs["include_dirs"] = [os.path.join(library, "include")]
        kwargs["library_dirs"] = [os.path.join(library, "lib")]
    return kwargs


def extensions_and_packages():
    utils = Extension("janus.utils.checkarray", sources=["janus/utils/checkarray.pyx"])
    operators = Extension("janus.operators", sources=["janus/operators.pyx"])
    materials = Extension(
        "janus.material.elastic.linear.isotropic",
        sources=["janus/material/elastic/linear/isotropic.pyx"],
    )

    kwargs = fftw_config()
    serial_fft = Extension(
        "janus.fft.serial._serial_fft",
        sources=["janus/fft/serial/_serial_fft.pyx"],
        **kwargs,
    )
    green = Extension("janus.green", sources=["janus/green.pyx"], **kwargs)
    extensions = [utils, operators, materials, green, serial_fft]
    packages = ["janus", "janus.fft", "janus.fft.serial", "janus.utils"]
    return extensions, packages


if __name__ == "__main__":
    extensions, packages = extensions_and_packages()

    setup(
        packages=packages,
        ext_modules=cythonize(
            extensions,
            compiler_directives={"embedsignature": True, "language_level": 3},
        ),
        cmdclass={"clean": clean},
    )
